config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',# このpathを通して外部API認証が行われる。
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  get "/" => "homes#top"
  get "/homes/about" => "homes#about"
  get "/homes/service" => "homes#service"
  get "/homes/privacy" => "homes#privacy"
  devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  post "links/:id/update" => "links#update"  
  delete "/links/:id" => "links#destroy"
  post "websites/:id/update" => "websites#update"  
  delete "/websites/:id" => "websites#destroy"
  post "subprofiles/:id/update" => "subprofiles#update"
  delete "/subprofiles/:id" => "subprofiles#destroy"
  resources :users, only: [:index, :show, :edit, :update]
  resources :links
  resources :websites
  resources :subprofiles
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController# 1ページの表示数
  PER_PAGE = 50
  def top
    @q = User.ransack(params[:q])
    @users = @q.result.order("created_at DESC").page(params[:page]).per(PER_PAGE)
    if user_signed_in?
      redirect_to("/users/#{current_user.id}")
    end
  end
  
  def about
  end

  def service
  end

  def privacy
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<p>申し訳ございません。準備中です。</p>

app/views/homes/privacy.html.erb
<div style="margin-bottom:100px;">
  <p style="margin:15px;">
  プライバシーポリシー
  1. 個人情報の定義
  kakikukekoでは、個人情報を次のように認識しています。

  個人情報の保護に関する法律に規定される生存する個人に関する情報（氏名、生年月日、その他の特定の個人を識別することができる情報）、ならびに特定の個人と結びついて使用されるメールアドレス、ユーザーID(アカウント)、パスワード、個体識別番号、クレジットカードなどの情報、および個人情報と一体となった趣味、家族構成、年齢その他の個人に関する属性情報である。

  2. 個人情報の管理
  ご利用者さまの個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備の徹底等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。

  3. cookie(クッキー)・IPアドレス情報
  cookie及びIPアドレス情報については、それら単独では特定の個人を識別することができないため、個人情報とは考えておりません。ただしこれら情報と個人情報が一体となって使用される場合にはこれら情報も個人情報とみなします。kakikukekoの運営するメディアにおいては、たとえ特定の個人を識別することができなくとも、cookie及びIPアドレス情報を利用する場合には、その目的と方法を開示してまいります。また、cookie情報については、ブラウザの設定で拒否することが可能です。cookieを拒否するとサービスが受けられない場合は、その旨も公表します。

  4. 個人情報の第三者への開示・提供の禁止
  kakikukekoは、あらかじめご本人の同意を得ず、利用目的の達成に必要な範囲を超えて個人情報を取扱うことはありません。合併その他の理由により個人情報を取得した場合にも、あらかじめご本人の同意を得ないで、承継前の利用目的の範囲を超えて取扱うことはありません。ただし、次の場合はこの限りではありません。

  法令に基づき開示することが必要である場合
  人の生命，身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき
  公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき
  国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
  予め次の事項を告知あるいは公表をしている場合
  (1) 利用目的に第三者への提供を含むこと
  (2) 第三者に提供されるデータの項目
  (3) 第三者への提供の手段または方法
  (4) ご本人の求めに応じて個人情報の第三者への提供を停止すること
  ただし次に掲げる場合は上記に定める第三者には該当しません。
  (1) kakikukekoが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
  (2) 合併その他の事由による事業の承継に伴って個人情報が提供される場合
  (3) 個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報 の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめご本人に通知し、またはご本人が容易に知り得る状態に置いているとき
  </p>
</div>

app/views/homes/service.html.erb
<div style="margin-bottom:100px;">
  <p style="margin:15px;">
  利用規約
  kakikukeko（以下、本サービス）の利用にあたって、本サービスを利用する全てのユーザー（以下、ユーザー）は以下の利用規約の全てに同意したものとみなします。
  本サービスは本規約を随時変更することができ、ユーザーはこれを了承するものとします。
  本サービスは提供するサービスの改善と品質保持に努めますが、サービスの絶対性/確実性/正確性/信頼性を保証するものではありません。
  本サービスは日本国内の法律に反する利用及び公序良俗に反する目的での利用を禁止します。また、発見次第該当データの削除を出来るものとします。
  プライバシー情報は原則として裁判所、警察及びそれに準じた法的機関からの要請に対しのみ開示を行うとし、原則としてユーザー本人の同意なく第三者に開示することはありません。

  免責事項
  運営が必要と判断した場合には、ユーザーに通知する事なくいつでも本サービスを停止、変更または中止、終了する事ができるものとし、ユーザーに対して一切責任を負わないものとします。
  本サービスの利用に関して、配信内容、トラブル等についての責任は一切関知致しません。リンク先、並びに本サービス以外が保有するサーバー以外に存在するサイトはその所有者・社によって管理されていますので、運営は一切の責任を負いかねます。
  運営は何らかの起因によるデータの消滅、破損の責任、保障は致しかねます。
  本サービスへ登録されたメールアドレスへ、本サービスからの新サービスの案内や必要な案内を配信させて頂く場合が御座います。ユーザーはこれを登録時に承諾したものとみなします。

  禁止事項
  日本国、及びそれ以外の国の法律、法令、条例に違反する行為
  無修正・児童ポルノ・著作権/肖像権に触れる等の法に違反する行為
  公序良俗に反する表現を含む行為
  プライバシーや著作権に反するもの、その他の権利を侵害する行為
  特定の個人や企業、団体、国、人種などへの誹謗中傷を含む行為
  過度に暴力的な表現、露骨な性的表現、人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現、自殺、自傷行為、薬物乱用を誘引または助長する表現、その他反社会的な内容を含み他人に不快感を与える表現を、投稿または送信する行為
  営業、宣伝、広告、勧誘、その他営利を目的とする行為（本サービスの認めたものを除きます。）、性行為やわいせつな行為を目的とする行為、面識のない異性との出会いや交際を目的とする行為、他のお客様に対する嫌がらせや誹謗中傷を目的とする行為、その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為
  サーバーに著しく負荷を与えるような利用
  宗教活動または宗教団体への勧誘行為
  ハッキング行為、ウィルス送信、スパムメール送信
  情報送信時の虚偽の申告
  作成したプロフィールの管理運営の放棄
  その他運営が不適当と判断した一切の行為
  ユーザーの責任
  ユーザーはプロフィールの内容、管理、著作権に関する一切の責任を負うこととします。
  禁止事項に該当する内容が発生した場合、ユーザーは当該内容を即刻その内容を消去する責任を負います。
  利用停止について
  禁止事項に該当する場合
  その他、運営が不適当と判断した場合
  </p>
</div>

app/views/homes/top.html.erb
<div class="top_coment_p">
    <p class="top_coment">プロフィールを作成して<br>リンクをまとめよう。</p>
    <p><%= link_to "新規登録", new_user_registration_path, class: "top_start_btn new" %></p>
    <p><%= link_to "ログイン", new_user_session_path, class: "top_start_btn login" %></p>
    <p><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></p>
    <!-- Twitterログイン-->
    <div style="text-align:center;margin-bottom:30px;">
      <%= link_to "/users/auth/twitter" do %>
        <div class="twitter_sigin_btn_p">
         <span class="fab fa-twitter" style="color:white;">   Twitterでログイン</span>
        </div>
      <% end %>
      <div style="margin-top:50px;">
       <p class="top_users_index_title">みんなのプロフィール</p>
      </div>
    </div>
</div>

<%= render 'users/index' %>